package gui.adminPanels.tipoPaneles;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

public class MultipleJP extends javax.swing.JPanel implements AdminJList {

    DefaultListModel<String> modeloCorrectas = new DefaultListModel(), modeloIncorrectas = new DefaultListModel();

    public MultipleJP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        multipleJPCorrectasEliminar = new javax.swing.JButton();
        multipleJPIncorrectasEliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        JScrollPane1 = new javax.swing.JScrollPane();
        multipleJPIncorrectas = new javax.swing.JList<String>(modeloIncorrectas);
        multipleJPIncorrectasAgregar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        multipleJPCorrectas = new javax.swing.JList<String>(modeloCorrectas);
        multipleJPCorrectasAgregar = new javax.swing.JButton();

        multipleJPCorrectasEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove.png"))); // NOI18N
        multipleJPCorrectasEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleJPCorrectasEliminarActionPerformed(evt);
            }
        });

        multipleJPIncorrectasEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove.png"))); // NOI18N
        multipleJPIncorrectasEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleJPIncorrectasEliminarActionPerformed(evt);
            }
        });

        jLabel11.setText("Respuestas incorrectas");

        multipleJPIncorrectas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JScrollPane1.setViewportView(multipleJPIncorrectas);

        multipleJPIncorrectasAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        multipleJPIncorrectasAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleJPIncorrectasAgregarActionPerformed(evt);
            }
        });

        jLabel10.setText("Respuestas correctas");

        multipleJPCorrectas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(multipleJPCorrectas);

        multipleJPCorrectasAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        multipleJPCorrectasAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleJPCorrectasAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(JScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multipleJPCorrectasAgregar)
                    .addComponent(multipleJPCorrectasEliminar)
                    .addComponent(multipleJPIncorrectasEliminar)
                    .addComponent(multipleJPIncorrectasAgregar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(multipleJPCorrectasAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multipleJPCorrectasEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(multipleJPIncorrectasAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multipleJPIncorrectasEliminar)))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void multipleJPCorrectasAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleJPCorrectasAgregarActionPerformed
        addItem(modeloCorrectas);
    }//GEN-LAST:event_multipleJPCorrectasAgregarActionPerformed

    private void multipleJPCorrectasEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleJPCorrectasEliminarActionPerformed
        removeItem(multipleJPCorrectas, modeloCorrectas);
    }//GEN-LAST:event_multipleJPCorrectasEliminarActionPerformed

    private void multipleJPIncorrectasAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleJPIncorrectasAgregarActionPerformed
        addItem(modeloIncorrectas);
    }//GEN-LAST:event_multipleJPIncorrectasAgregarActionPerformed

    private void multipleJPIncorrectasEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleJPIncorrectasEliminarActionPerformed
        removeItem(multipleJPIncorrectas, modeloIncorrectas);
    }//GEN-LAST:event_multipleJPIncorrectasEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> multipleJPCorrectas;
    private javax.swing.JButton multipleJPCorrectasAgregar;
    private javax.swing.JButton multipleJPCorrectasEliminar;
    private javax.swing.JList<String> multipleJPIncorrectas;
    private javax.swing.JButton multipleJPIncorrectasAgregar;
    private javax.swing.JButton multipleJPIncorrectasEliminar;
    // End of variables declaration//GEN-END:variables
}
